apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: argocd-demo
  namespace: kcm-system
spec:
  clusterSelector:
    matchLabels:
      env: demo
  serviceSpec:
    services:
      - name: argocd-demo-service
        namespace: argocd
        template: argo-cd-8-6-1
